# install_node_exporter.yml
- name: Node Exporter Installation Playbook
  hosts: "{{ host_group }}"
  become: true
  vars:
    node_exporter_version: "1.6.1"
    node_exporter_download_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    node_exporter_install_dir: "/usr/local/bin"
    node_exporter_user: "node_exporter"

  tasks:
  
    - name: Create node_exporter user
      user:
        name: "{{ node_exporter_user }}"
        system: true
        shell: /usr/sbin/nologin

    - name: Download Node Exporter binary
      get_url:
        url: "{{ node_exporter_download_url }}"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"

    - name: Extract Node Exporter binary
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.tar.gz"
        dest: "/tmp"
        remote_src: yes

    - name: Move Node Exporter binary to /usr/local/bin
      copy:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
        dest: "{{ node_exporter_install_dir }}/node_exporter"
        owner: "{{ node_exporter_user }}"
        mode: "0755"
        remote_src: yes


    - name: Create Node Exporter systemd service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          Wants=network-online.target
          After=network-online.target

          [Service]
          User={{ node_exporter_user }}
          ExecStart={{ node_exporter_install_dir }}/node_exporter
          Restart=always

          [Install]
          WantedBy=default.target
      notify: Restart node_exporter

    - name: Enable and start Node Exporter service
      systemd:
        name: node_exporter
        enabled: yes
        state: started

  handlers:
    - name: Restart node_exporter
      systemd:
        name: node_exporter
        state: restarted
