- name: Set up NFS clients
  hosts: "{{ host_group }}"
  become: true
  vars:
    nfs_server_ip: "{{ nfs_server_ip }}"
    nfs_mount_path: "{{ nfs_mount_path }}"
  tasks:
    - name: Install NFS client package
      apt:
        name: nfs-common
        state: present
        update_cache: true

    - name: Create mount point
      file:
        path: "{{ nfs_mount_path }}"
        state: directory
        mode: '0755'

    - name: Mount NFS share
      mount:
        path: "{{ nfs_mount_path }}"
        src: "{{ nfs_server_ip }}:{{ nfs_export_path }}"
        fstype: nfs
        state: mounted
        opts: rw,sync
