######## ALL #########
- import_playbook: ./init/host_configuration.yaml
  vars:
    host_group: all

- import_playbook: ./installations/install_root_ca/install_root_ca.yaml
  vars:
    host_group: all

- import_playbook: ./installations/install_docker.yaml
  vars:
    host_group: all

# - import_playbook: ./installations/install_node-exporter.yaml
#   vars:
#     host_group: all