- name: Configure iptables for SSH with IP ranges
  hosts: all
  become: yes
  tasks:
    - name: Flush existing iptables rules (optional, for a clean start)
      command: iptables -F

    - name: Allow SSH from specific IP ranges
      iptables:
        chain: INPUT
        source: "{{ item }}"
        protocol: tcp
        destination_port: 22
        jump: ACCEPT
      loop:
        - 192.168.1.0/24
        - 10.0.0.0/16

    - name: Allow HTTP
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT

    - name: Allow HTTPS
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 443
        jump: ACCEPT

    - name: Drop all other incoming traffic
      iptables:
        chain: INPUT
        jump: DROP

    - name: Allow established and related connections
      iptables:
        chain: INPUT
        match: state
        state: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Save iptables rules
      command: iptables-save > /etc/iptables/rules.v4
