- name: Install and Start NGINX
  hosts: nginx_servers
  become: true  # Run as sudo
  tasks:
    - name: Update apt package list (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    
    - name: Check if NGINX is installed
      command: dpkg -l nginx
      register: nginx_installed
      ignore_errors: true

    - name: Install NGINX on Debian/Ubuntu
      ansible.builtin.apt:
        name: nginx
        state: present
      when: nginx_installed.rc != 0

    - name: Start and enable NGINX service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
      when: nginx_installed.rc != 0

    - name: Copy all .conf files from local to remote
      copy:
        src: ../files/install_nginx/main.conf   # Copy all .conf files in this directory
        dest: /etc/nginx/sites-enabled/      # Destination directory on remote machine
        owner: root
        group: root
        mode: '0644'
        remote_src: no                       # Indicates source is local (not on the remote system)

    - name: Ensure NGINX is reloaded to apply new configuration
      systemd:
        name: nginx
        state: reloaded

