######### Jenkins #########
- import_playbook: ./installations/install_dotnetcore.yaml
  vars:
    host_group: jenkins_servers

- import_playbook: ./installations/install_trivy.yaml
  vars:
    host_group: jenkins_servers

- import_playbook: ./installations/install_jenkins.yaml
  vars:
    host_group: jenkins_servers