---
######## ALL #########
- import_playbook: ./init/host_configuration.yaml
  vars:
    host_group: all

# - import_playbook: ./installations/install_root_ca/install_root_ca.yaml
#   vars:
#     host_group: all

# - import_playbook: ./installations/install_node-exporter.yaml
#   vars:
#     host_group: all

- import_playbook: ./installations/install_docker.yaml
  vars:
    host_group: all

######## K8S #########
- import_playbook: ./init/post_server.yaml
  vars:
    host_group: k8s_servers

######### Utility #########
# - import_playbook: ./installations/install_harbor/install_harbor.yaml
#   vars:
#     host_group: utility_servers
#     harbor_domain: "utility.ndkn.local"
#     harbor_admin_password: "admin123"

# - import_playbook: ./runs/run_grafana/run_grafana.yaml
#   vars:
#     host_group: utility_servers

######### Jenkins #########
# - import_playbook: ./installations/install_dotnetcore.yaml
#   vars:
#     host_group: jenkins_servers

# - import_playbook: ./installations/install_trivy.yaml
#   vars:
#     host_group: jenkins_servers

# - import_playbook: ./installations/install_jenkins.yaml
#   vars:
#     host_group: jenkins_servers
