---
- name: Setup Jenkins
  hosts: all
- import_playbook: install_dotnetcore.yaml
  vars:
    host_group: jenkins_servers

- import_playbook: install_docker.yaml
  vars:
    host_group: jenkins_servers

- import_playbook: install_trivy.yaml
  vars:
    host_group: jenkins_servers

# - import_playbook: install_node-exporter.yaml
#   vars:
#     host_group: jenkins_servers

- import_playbook: install_jenkins.yaml
  vars:
    host_group: jenkins_servers
