- import_playbook: ./init/host_configuration.yaml
  vars:
    host_group: all

# - import_playbook: ./init/docker_login.yaml
#   vars:
#     host_group: jenkins_servers
#     registry_url: utility.ndkn.local
#     registry_username: admin
#     registry_password: admin123