# - import_playbook: ./installations/install_ssh_public_key.yaml
#   vars:
#     host_group: all
#     ssh_public_key : ssh-rsa <publickey> kn@ndkn

# - import_playbook: ./init/docker_login.yaml
#   vars:
#     host_group: jenkins_servers
#     registry_url: utility.ndkn.local
#     registry_username: admin
#     registry_password: admin123

# - import_playbook: ./installations/install_docker.yaml
#   vars:
#     host_group: all

# - import_playbook: ./runs/run_gitea/run_gitea.yaml
#   vars:
#     host_group: all


- import_playbook: ./installations/install_keepalived/install_keepalived.yaml
  vars:
    host_group: all
    interface: eth1
    auth_pass: "12345678"
    vip: "192.168.121.100/24"
    state: MASTER
    router_id: 51